# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='verdict',
            field=models.IntegerField(choices=[(100, 'Yay'), (50, 'Meh'), (0, 'Nah')], default=0),
        ),
    ]
