# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20180306_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.Category'),
            preserve_default=False,
        ),
    ]
